VEEQO_ORDERS_URL = "https://api.veeqo.com/orders"
VEEQO_PRODUCTS_URL = "https://api.veeqo.com/products"
POSTCODER_URL = "https://ws.postcoder.com"

TAX_RATE = 0.2

DEFAULT_DELIVERY_METHOD_ID = "153707"

BANDQ_CHANNEL_ID = "48307"
ARGOS_CHANNEL_ID = "46116"
RANGE_CHANNEL_ID = "55732"
HOMEBASE_CHANNEL_ID = "46687"
