import CardComponent from "./shared/CardComponent";
import HeaderComponent from "./shared/HeaderComponent";
import JumbotronComponent from "./shared/JumbotronComponent";
import SelectComponents from "./shared/SelectComponents";
import SelectFormComponent from "./shared/SelectFormComponent";
import SpinnerComponent from "./shared/SpinnerComponent";
import MultiSelectComponent from "./shared/MultiSelectComponent";
import IconButtonComponent from "./shared/IconButtonComponent";
import InlineButtonComponent from "./shared/InlineButtonComponent";
import IconHeaderComponent from "./shared/IconHeaderComponent";

export const Card = CardComponent;
export const Header = HeaderComponent;
export const Jumbotron = JumbotronComponent;
export const Select = SelectComponents;
export const SelectForm = SelectFormComponent;
export const Spinner = SpinnerComponent;
export const MultiSelect = MultiSelectComponent;
export const IconButton = IconButtonComponent;
export const InlineButton = InlineButtonComponent;
export const IconHeader = IconHeaderComponent;
